### ISSUE TITLE
Squashed heatmap

### ISSUE THREAD

**Issue by jariji** [JuliaAPlavin/AxisKeysExtra.jl#2]
```jl
using AxisKeys, CairoMakie, AxisKeysExtra
ka = KeyedArray(rand(10,3), γ=range(1.0E-5, 1.0E-3; length=10), λ=.02:.02:.06)
2-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   γ ∈ 10-element StepRangeLen{Float64,...}
→   λ ∈ 3-element StepRangeLen{Float64,...}
And data, 10×3 Matrix{Float64}:
            (0.02)       (0.04)       (0.06)
 (1.0e-5)     0.982858     0.784465     0.513582
 (0.00012)    0.689553     0.921182     0.0734911
 (0.00023)    0.417205     0.0777437    0.338265
 (0.00034)    0.183156     0.574842     0.692046
 (0.00045)    0.515173     0.215511     0.834362
 (0.00056)    0.172164     0.491808     0.124911
 (0.00067)    0.929363     0.244076     0.360465
 (0.00078)    0.235326     0.11955      0.289142
 (0.00089)    0.824409     0.131883     0.0372121
 (0.001)      0.0733502    0.607193     0.41637
hm = heatmap(ka)
```

![image](https://github.com/user-attachments/assets/0ba3fd8d-e423-4962-ac27-8ee94d7c825d)

**Comment by aplavin** [comment]
Whenever units (in the Unitful sense) for both axes are the same, it does set `aspect=DataAspect()`. It makes total sense for actual unitful axes, but probably not for plain numbers... I just always happen to have units in my axes I guess :)

Will change so that it doesn't set aspect for plain numbers.

**Comment by aplavin** [comment]
Fixed, now aspect is only set when units are actually present (and equal, of course).

Btw, you can and could always override these default parameters, as in regular Makie: either `heatmap(..., axis=(aspect=1,))` or `fig, ax, plt = heatmap(...); ax.aspect = 1`.
